name: PR Commands

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier:
    name: Format files with prettier
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/trigger')
    steps:
      - name: ğŸŒ¿ Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: ğŸŸ¡ Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          status: pending

      - name: ğŸ“„ Create comment
        uses: peter-evans/create-or-update-comment@v3
        id: create-comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Autoformatting files started ğŸ”¨

      - name: â¬ Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: ğŸ‘ React with thumps up to comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: "+1"

      - name: âš« Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}

      - name: ğŸ“„ Create success comment
        uses: peter-evans/create-or-update-comment@v3
        if: success()
        with:
          comment-id: ${{ steps.create-comment.outputs.comment-id }}
          body: Autoformatting done! ğŸš€

      - name: ğŸ“„ Create failure comment
        uses: peter-evans/create-or-update-comment@v3
        if: failure()
        with:
          comment-id: ${{ steps.create-comment.outputs.comment-id }}
          body: |
            Autoformatting failed! âŒ

            For more details, see the workflow output: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
